# .github/workflows/sca.yml
name: SCA — Trivy

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

permissions:
  security-events: write
  contents: read

jobs:

  trivy-fs:
    name: Trivy — Dependencias
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy — escaneo de dependencias
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: "."
          format: sarif
          output: trivy-fs.sarif
          severity: CRITICAL,HIGH
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: library

      - name: Subir SARIF dependencias
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

      - name: Trivy — reporte tabla
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          scan-type: fs
          scan-ref: "."
          format: table
          severity: CRITICAL,HIGH,MEDIUM

  trivy-image:
    name: Trivy — Imagen Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build imagen Docker
        run: docker build -t devsecops-lab:${{ github.sha }} .

      - name: Trivy — escaneo imagen
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: devsecops-lab:${{ github.sha }}
          format: sarif
          output: trivy-image.sarif
          severity: CRITICAL,HIGH
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: os,library

      - uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image

      - name: Guardar imagen
        run: docker save devsecops-lab:${{ github.sha }} | gzip > image.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz
          retention-days: 1